feat: create a new community
The-Agile-Avengers/icu-connect-frontend pull request #156
Opened 2023-04-09 11:00 UTC by Mariinja

closes #10

2023-04-09 13:23 UTC, Taremeh commented on src/components/course/CommunityCreate.tsx
> +        width: "100%",}}
```suggestion
      spacing={4}
      sx={{width: "100%"}}
```

2023-04-09 13:29 UTC, Taremeh requested changes
The component is wrapped by a `Layout` Component (line 70) in the `CommunityCreate.tsx` file and wrapped again in a `Layout` Component in the `Community.tsx` file (line 277). Considering, that for we've wrapped the components in `Community.tsx` for every other if/else case, it would make sense to remove the Layout wrapping here. If React complains due to the single child element constraint, you can instead wrap it using "<> .... </>" which is common practice in React.

2023-04-11 07:58 UTC, StefanieKrohmann commented on src/components/course/CreateCommunityForm.tsx
> +    console.log(formData)
duplicate console.log()

2023-04-11 07:59 UTC, StefanieKrohmann commented on src/components/course/CreateCommunityForm.tsx
> +  console.log(formData)
duplicate console.log()

2023-04-11 08:05 UTC, StefanieKrohmann submitted a review, later dismissed
👍

2023-04-12 11:31 UTC, StefanieKrohmann approved these changes

2023-04-13 12:04 UTC, Taremeh approved these changes
👍👍👍

2023-04-14 05:26 UTC, merged